baseURL = "https://phlegmatreec.com/"
languageCode = 'en-us'
title = "PhlegmaTRREc's site"
theme = 'gokarna'

enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "about"
    url = "/about/"
    name = "About"
    weight = 1
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"
    url = "/posts/"
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # Display name
    name = "Posts"
    # Weights are used to determine the ordering
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/PhlegmaTREEc"
    weight = 4
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/site_logo.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "Welcome to my site. This early work in progress."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo", "phlegmatreec"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = ""

  # Footer text
  footer = "PhlegaTREEc"
